services: 
  app:
    build:
      context: ./frontend
    ports:
      - "3000:${NEXT_PORT}"
    environment:
      NEXT_PORT: ${NEXT_PORT}
    restart: unless-stopped

#docker-compose up --build
#docker-compose down